# SQLite version 3.x
#   gem 'activerecord-jdbcsqlite3-adapter'
#
# Configure Using Gemfile
# gem 'activerecord-jdbcsqlite3-adapter'
#
default: &default
  adapter: postgresql
  prepared_statements: false
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  reaping_frequency: 10

development:
  <<: *default
  database: invaincu_db
  pool: <%= ENV['DB_POOL'] || 5 %>
production:
  <<: *default
  database: invaincu_db
  pool: <%= ENV['DB_POOL'] || 5 %>
